### PR TITLE
Adding reset Command to clear old data and restore node

### PR DESCRIPTION
**Pull request by oten91**
usage : 
`./pocket-core reset`

Clears 
- .pocket/data
- priv_val_key
- priv_val_state
- node_keys

### CODE REVIEW

**Review by luyzdeleon — DISMISSED** [review]
Missing update to RPC Spec documentation

**Review by oten91 — COMMENTED** [review]
Changes made!

**Review by andrewnguyen22 — DISMISSED** [review]
Why did you comment out the dbpath?

**Comment by oten91** [comment]
> Why did you comment out the dbpath?

to make it so that all the databases tendermint creates are stored on ./pocket/data/ and not on ./pocket/

we get a cleaner home folder this way.

image

**Review by andrewnguyen22 — APPROVED** [review]

**Pull request merged**
