### PR TITLE
Patch 3

### PR DESCRIPTION
**Pull request by BenVanGithub**

### CODE REVIEW

**Comment by BenVanGithub** [comment]
Added context info to every command where appropriate,  
Tested every command by hand when done.
=======  4 NOTES FOR REVIEW PLEASE ===
1.)  I built a little struct to unmarshal height (see line 17) because I'm still having difficulty finding the correct structures in the repository.  It is only used one time.  Please replace it, or point me to where the proper struct is.
2.)  Modified the query block command to return the current block if no height is provided (lines 63-71)
3.)  Also in the query block command.. there was a work around for a typecasting problem which I changed to use strconv.ParseInt(args[0],10,64).. It just feels cleaner (Line 74)
4.)  Opened a separate issue about the command query daoOwner (it doesn't work)

This PR partially addresses #1082 but does not close it.

**Comment by andrewnguyen22** [comment]
Hey @BenVanGithub 

Thanks for this.

Before merging:

1) [Here's the height param structure you were asking to replace](https://github.com/pokt-network/pocket-core/blob/5a26ae0f2fc69b523581e1e3ccb30b04d3ad062c/app/cmd/rpc/query.go#L23)
2) Random `res = res` on L74
3) We want to avoid the CLI doing two requests in one. We should modify the server code where if height == 0 use latest height instead of doing two requests:
```
res, err := QueryRPC(GetHeightPath, []byte{})
			if err != nil {
				fmt.Println(err)
				return
			}
			json.Unmarshal([]byte(res), &currentHeight)
			height = currentHeight.Height
```

**Comment by BenVanGithub** [comment]
>     3. We want to avoid the CLI doing two requests in one. We should modify the server code where if height == 0 use latest height instead of doing two requests:
> 
Totally agree.  It was kinda hacky to include that change on the same PR with the rest of that anyway... I'm still getting the hang of github... have a few questions for the Thursday meeining.

**Comment by andrewnguyen22** [comment]
Awesome, I'll keep an eye on this for edits

**Comment by andrewnguyen22** [comment]
@BenVanGithub will resubmit this PR

**Pull request closed without merging**
