### PR TITLE
Entering and Exiting The Network Message Construction and Handling

### LINKED ISSUE #97: Service Node: Exit Network Message
Allow the service node to gracefully exit the network by notifying the dispatcher

### LINKED ISSUE #98: Dispatcher: Exit Network Message
Receive and process exit network message from service nodes

### LINKED ISSUE #100: Service Node: Registration Message
Register the SN within the centralized dispatcher via UDP message

### PR DESCRIPTION
**Pull request by andrewnguyen22**
closes #97 
closes #98 
closes #100

### CODE REVIEW

**Review by iajrz — COMMENTED** [review]
Issue #100 states that the message is UDP - but I don't see that reflected in the code or TODO comments. Furthermore, we should make sure that the message arrives - shouldn't this be a TCP message?
I don't see how we'd send it, or handle failure to get to the Dispatcher - which I think should cause the program to crash loudly and complain about unavailability.

**Comment by andrewnguyen22** [comment]
Hey @iajrz! So this is using UDP (code found in message/connection.go) MSGTYPE constant is "udp" 

Regardless, I actually agree that TCP would most likely be better for liveness checks (if it's not too much trouble to maintain each conn lifecycle. However, that was not what was laid out in the original issues we had all agreed to. Thus, I move to approve this issue and then we can create a new issue in the next sprint!

**Review by iajrz — DISMISSED** [review]

**Comment by iajrz** [comment]
@andrewnguyen22 Approved; the rebasing needs manual work. (sorry!)

**Comment by andrewnguyen22** [comment]
Hahaha no problem @iajrz ! I knew that this was going to happen for each PR LOL

**Pull request merged**
