### PR TITLE
Issue #189

### LINKED ISSUE #189: Create generic Dockerfile
Create a Dockerfile that tests the code, and builds a binary.

Connected to Pocket Network's Docker HUB: https://cloud.docker.com/u/poktnetwork/repository/registry-1.docker.io/poktnetwork/pocket-core

### PR DESCRIPTION
**Pull request by luyzdeleon**
Closes #189 

This PR generated a backlogged issue #191 to be implemented at a later date.

### CODE REVIEW

**Comment by andrewnguyen22** [comment]
Can we move the dockerfile into the build directory?
See initial request at #189

**Comment by luyzdeleon** [comment]
> Can we move the dockerfile into the build directory?
> See initial request at #189

It is standard practice to have `Dockerfile` in the root of the directory, as many build automation services look there for automation integrations.

**Comment by andrewnguyen22** [comment]
> > Can we move the dockerfile into the build directory?
> > See initial request at #189
> 
> It is standard practice to have `Dockerfile` in the root of the directory, as many build automation services look there for automation integrations.

Yeah after doing a quick search I found this to be true. However, we do have a build dir for config files as such.

**Comment by andrewnguyen22** [comment]
In any case, let's leave it at root for now

**Review by andrewnguyen22 — APPROVED** [review]

**Pull request merged**
