### PR TITLE
Issue #174

### LINKED ISSUE #174: Periodically read from the database (dynamodb)
@luyzdeleon @iajrz any idea how often we want this to happen?

### LINKED ISSUE #177: Upgrade message built into the dispatcher
Life cycle prediction leads us to believe that MVP to testnet will need a major upgrade, hence we will pre-build in the mechanism to allow the dispatchers to signal the end of the MVP era

### LINKED ISSUE #178: Reads and Writes from peerlist to db need to be atomic
Race condition currently exists between peerlist and db

### LINKED ISSUE #179: Remove unnecessary print statements throughout for QOL
Any println() that aren't needed are just confusing to the user

### PR DESCRIPTION
**Pull request by andrewnguyen22**
Closes #174 
Closes #177 
Closes #178 
Closes #179

### CODE REVIEW

**Comment by andrewnguyen22** [comment]
One thing to look out for -> we are persisting one dynamodb session throughout the life of the program. I don't see anything in the documentation to go against this methodology. However, we should keep this in mind incase there are problems in the future.

https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/sessions.html

**Comment by iajrz** [comment]
> One thing to look out for -> we are persisting one dynamodb session throughout the life of the program. I don't see anything in the documentation to go against this methodology. 

Good call; this is recommended:

>Sessions should be cached when possible, because creating a new Session will load all configuration values from the environment, and config files each time the Session is created. Sharing the Session value across all of your service clients will ensure the configuration is loaded the fewest number of times possible

https://docs.aws.amazon.com/sdk-for-go/api/aws/session/#pkg-overview

**Comment by andrewnguyen22** [comment]
Right so I'm pretty sure this is exactly what I coded. Double check me though ;)

**Comment by iajrz** [comment]
I'm on it 😅

**Review by iajrz — COMMENTED** [review]
Looks good; maybe I'll slate the DisMode numbers to be moved into constants, but otherwise looks good to me. Do you think it's a good time to make the numbers named constants, or can it be done later?

**Comment by andrewnguyen22** [comment]
On it ;)

**Comment by andrewnguyen22** [comment]
Okay done!

**Review by iajrz — APPROVED** [review]

**Pull request merged**
