### PR TITLE
Reproducible build

### PR DESCRIPTION
**Pull request by edjroz**
- Add a make file to make developer interaction with the project easier. 
- Add docker file to build and run the node.

P.D: The docker file should be considered as only a very early alpha due to the use of the `latest` tag and no optimal optimization for the node.

The Make file can also be improved by:

```Makefile
GO_MAKEFILE_VERSION := 1.11.0
REPOSITORY := $(pwd)
SRC := /gopath/src/$(REPOSITORY)

ifndef DOCKER_IMAGE
	DOCKER_IMAGE := golang:$(GO_MAKEFILE_VERSION)
endif
DOCKER_RUN := docker run --rm -v $(shell pwd):$(SRC) -w $(SRC)  $(DOCKER_IMAGE)

build:  
    @(DOCKER_RUN) /bin/bash -c 'go build -o core ./cmd/pocket_core/main.go'

```

As this would make sure all developers build the same app (however if done it would require refactoring on the docker file as to not use the make command).

### CODE REVIEW

**Review by luyzdeleon — DISMISSED** [review]

**Comment by luyzdeleon** [comment]
@edjroz Please resolve the merge conflicts before we can merge this.

**Comment by edjroz** [comment]
@luyzdeleon Thanks for reviewing, latest commit was a merge to solve it. 🙂

**Comment by luyzdeleon** [comment]
@edjroz we made some changes (we're in an active sprint at the moment), so that created some new conflicts, update your fork with the latest from `staging` and you can resolve the conflicts and update this PR.

**Review by andrewnguyen22 — DISMISSED** [review]
If you rebase then this is approved

**Comment by edjroz** [comment]
@andrewnguyen22 could you elaborate on what would would need to be rebased? would you like commits from the change to be on the top?

**Comment by luyzdeleon** [comment]
@edjroz The Pull Request is not able to be merged because of the following message:

This branch cannot be rebased due to conflicts
Rebasing the commits of this branch on top of the base branch cannot be performed automatically due to conflicts encountered while reapplying the individual commits from the head branch.

**Comment by edjroz** [comment]
@luyzdeleon  @andrewnguyen22  Is there any other way to contact you guys to collaborate ? I've cloned the repo again and perform the merge without the error message.

**Review by andrewnguyen22 — APPROVED** [review]

**Pull request closed without merging**
