### PR TITLE
Removing Empty Proof Object from RequestHash,

### LINKED ISSUE #742: Empty proof object in request hash
Fix here:

```
relay := Relay{
func (r Relay) RequestHash() []byte {
		Payload: r.Payload,
		Meta:    r.Meta,
	}

```

### PR DESCRIPTION
**Pull request by oten91**
Changed from Relay to an anonymous struct to remove the empty proof object being generated

Closes #742

### CODE REVIEW

**Review by edjroz — DISMISSED** [review]
LGTM!

**Review by andrewnguyen22 — CHANGES_REQUESTED** [review]
I notice that the payload bytes() function has an empty headers object, can you use omit instead?

```
func (p Payload) Bytes() []byte {
	bz, err := json.Marshal(Payload{Data: p.Data, Method: p.Method, Path: p.Path})
	if err != nil {
		panic(fmt.Sprintf("an error occured converting the payload to bytes:\n%v", err))
	}
	return bz
}

```

**Comment by oten91** [comment]
> I notice that the payload bytes() function has an empty headers object, can you use omit instead?
> 
> ```
> func (p Payload) Bytes() []byte {
> 	bz, err := json.Marshal(Payload{Data: p.Data, Method: p.Method, Path: p.Path})
> 	if err != nil {
> 		panic(fmt.Sprintf("an error occured converting the payload to bytes:\n%v", err))
> 	}
> 	return bz
> }
> ```
Added omitempty!

**Review by oten91 — COMMENTED** [review]
@andrewnguyen22 Changes made

**Review by andrewnguyen22 — APPROVED** [review]

**Pull request merged**
