### PR TITLE
Allow read-only config.json, chains.json

### PR DESCRIPTION
**Pull request by lander2k2**
Issue: #1391

### CODE REVIEW

**Comment by iajrz** [comment]
Hey, just a heads up: this is in my radar; there's something to check with regards to the generation of empty `chains.json` when there are no chains -- a corner case, really; this is in my radar, though. Thanks!

**Comment by iajrz** [comment]
This is the same as #1392 ; I will close that one.

**Comment by lander2k2** [comment]
@iajrz commit added for read-only chains.json.  I think we're good to go now.

**Comment by oten91** [comment]
Hey @lander2k2 can you check the conflict?

**Comment by lander2k2** [comment]
@oten91 conflict resolved

**Review by oten91 — APPROVED** [review]

**Pull request merged**
